version: "3.8"
services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"

  frontend:
    build: .
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
